/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package shortcut;

/**
 *
 * @author lucas
 */
public class Tischverwaltung extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Tischverwaltung.class.getName());

    /**
     * Creates new form Tischverwaltung
     */
    public Tischverwaltung() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UeberschriftLabel = new javax.swing.JLabel();
        Tisch3Panel = new javax.swing.JPanel();
        Tisch3NameLabel = new javax.swing.JLabel();
        Tisch3StatusLabel = new javax.swing.JLabel();
        Tisch3PersonenLabel = new javax.swing.JLabel();
        Tisch1Panel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Tisch1StatusLabel = new javax.swing.JLabel();
        Tisch1PersonenLabel = new javax.swing.JLabel();
        Tisch2Panel = new javax.swing.JPanel();
        Tisch2NameLabel = new javax.swing.JLabel();
        Tisch2StatusLabel = new javax.swing.JLabel();
        Tisch2PersonenLabel = new javax.swing.JLabel();
        Tisch4Panel = new javax.swing.JPanel();
        Tisch4NameLabel = new javax.swing.JLabel();
        Tisch4StatusLabel = new javax.swing.JLabel();
        Tisch4PersonenLabel = new javax.swing.JLabel();
        Tisch5Panel = new javax.swing.JPanel();
        Tisch5NameLabel = new javax.swing.JLabel();
        Tisch5StatusLabel = new javax.swing.JLabel();
        Tisch5PersonenLabel = new javax.swing.JLabel();
        Tisch6Panel = new javax.swing.JPanel();
        Tisch6NameLabel = new javax.swing.JLabel();
        Tsich6StatusLabel = new javax.swing.JLabel();
        Tisch6PersonenLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UeberschriftLabel.setText("Tischverwaltung");

        Tisch3Panel.setBackground(new java.awt.Color(51, 255, 51));
        Tisch3Panel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Tisch3NameLabel.setText("Tisch 3");

        Tisch3StatusLabel.setText("frei");

        Tisch3PersonenLabel.setText("2 Personen");

        javax.swing.GroupLayout Tisch3PanelLayout = new javax.swing.GroupLayout(Tisch3Panel);
        Tisch3Panel.setLayout(Tisch3PanelLayout);
        Tisch3PanelLayout.setHorizontalGroup(
            Tisch3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tisch3PanelLayout.createSequentialGroup()
                .addGroup(Tisch3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Tisch3PanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(Tisch3NameLabel))
                    .addGroup(Tisch3PanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(Tisch3PersonenLabel))
                    .addGroup(Tisch3PanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Tisch3StatusLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Tisch3PanelLayout.setVerticalGroup(
            Tisch3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tisch3PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tisch3NameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Tisch3StatusLabel)
                .addGap(18, 18, 18)
                .addComponent(Tisch3PersonenLabel)
                .addContainerGap())
        );

        Tisch1Panel.setBackground(new java.awt.Color(51, 255, 51));
        Tisch1Panel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setText("Tisch 1");

        Tisch1StatusLabel.setText("frei");

        Tisch1PersonenLabel.setText("4 Personen");

        javax.swing.GroupLayout Tisch1PanelLayout = new javax.swing.GroupLayout(Tisch1Panel);
        Tisch1Panel.setLayout(Tisch1PanelLayout);
        Tisch1PanelLayout.setHorizontalGroup(
            Tisch1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tisch1PanelLayout.createSequentialGroup()
                .addGroup(Tisch1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Tisch1PanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5))
                    .addGroup(Tisch1PanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(Tisch1PersonenLabel))
                    .addGroup(Tisch1PanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Tisch1StatusLabel)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        Tisch1PanelLayout.setVerticalGroup(
            Tisch1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tisch1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(Tisch1StatusLabel)
                .addGap(18, 18, 18)
                .addComponent(Tisch1PersonenLabel)
                .addContainerGap())
        );

        Tisch2Panel.setBackground(new java.awt.Color(51, 255, 51));
        Tisch2Panel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Tisch2NameLabel.setText("Tisch 2");

        Tisch2StatusLabel.setText("frei");

        Tisch2PersonenLabel.setText("4 Personen");

        javax.swing.GroupLayout Tisch2PanelLayout = new javax.swing.GroupLayout(Tisch2Panel);
        Tisch2Panel.setLayout(Tisch2PanelLayout);
        Tisch2PanelLayout.setHorizontalGroup(
            Tisch2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tisch2PanelLayout.createSequentialGroup()
                .addGroup(Tisch2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Tisch2PanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(Tisch2NameLabel))
                    .addGroup(Tisch2PanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(Tisch2PersonenLabel))
                    .addGroup(Tisch2PanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Tisch2StatusLabel)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        Tisch2PanelLayout.setVerticalGroup(
            Tisch2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tisch2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tisch2NameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Tisch2StatusLabel)
                .addGap(18, 18, 18)
                .addComponent(Tisch2PersonenLabel)
                .addContainerGap())
        );

        Tisch4Panel.setBackground(new java.awt.Color(255, 51, 51));
        Tisch4Panel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Tisch4NameLabel.setText("Tisch 4");

        Tisch4StatusLabel.setText("belegt");

        Tisch4PersonenLabel.setText("4 Personen");

        javax.swing.GroupLayout Tisch4PanelLayout = new javax.swing.GroupLayout(Tisch4Panel);
        Tisch4Panel.setLayout(Tisch4PanelLayout);
        Tisch4PanelLayout.setHorizontalGroup(
            Tisch4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tisch4PanelLayout.createSequentialGroup()
                .addGroup(Tisch4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Tisch4PanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(Tisch4PersonenLabel))
                    .addGroup(Tisch4PanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(Tisch4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Tisch4StatusLabel)
                            .addComponent(Tisch4NameLabel))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        Tisch4PanelLayout.setVerticalGroup(
            Tisch4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tisch4PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tisch4NameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(Tisch4StatusLabel)
                .addGap(18, 18, 18)
                .addComponent(Tisch4PersonenLabel)
                .addContainerGap())
        );

        Tisch5Panel.setBackground(new java.awt.Color(51, 255, 51));
        Tisch5Panel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Tisch5NameLabel.setText("Tisch 5");

        Tisch5StatusLabel.setText("frei");

        Tisch5PersonenLabel.setText("7 Personen");

        javax.swing.GroupLayout Tisch5PanelLayout = new javax.swing.GroupLayout(Tisch5Panel);
        Tisch5Panel.setLayout(Tisch5PanelLayout);
        Tisch5PanelLayout.setHorizontalGroup(
            Tisch5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tisch5PanelLayout.createSequentialGroup()
                .addGroup(Tisch5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Tisch5PanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(Tisch5NameLabel))
                    .addGroup(Tisch5PanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(Tisch5PersonenLabel))
                    .addGroup(Tisch5PanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Tisch5StatusLabel)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        Tisch5PanelLayout.setVerticalGroup(
            Tisch5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tisch5PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tisch5NameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(Tisch5StatusLabel)
                .addGap(18, 18, 18)
                .addComponent(Tisch5PersonenLabel)
                .addContainerGap())
        );

        Tisch6Panel.setBackground(new java.awt.Color(51, 255, 51));
        Tisch6Panel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Tisch6NameLabel.setText("Tisch 6");

        Tsich6StatusLabel.setText("frei");

        Tisch6PersonenLabel.setText("4 Personen");

        javax.swing.GroupLayout Tisch6PanelLayout = new javax.swing.GroupLayout(Tisch6Panel);
        Tisch6Panel.setLayout(Tisch6PanelLayout);
        Tisch6PanelLayout.setHorizontalGroup(
            Tisch6PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tisch6PanelLayout.createSequentialGroup()
                .addGroup(Tisch6PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Tisch6PanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(Tisch6NameLabel))
                    .addGroup(Tisch6PanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(Tisch6PersonenLabel))
                    .addGroup(Tisch6PanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Tsich6StatusLabel)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        Tisch6PanelLayout.setVerticalGroup(
            Tisch6PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tisch6PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tisch6NameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(Tsich6StatusLabel)
                .addGap(18, 18, 18)
                .addComponent(Tisch6PersonenLabel)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Tisch4Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Tisch5Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Tisch6Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Tisch1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tisch2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(UeberschriftLabel)))
                        .addGap(18, 18, 18)
                        .addComponent(Tisch3Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(UeberschriftLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Tisch3Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Tisch1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Tisch2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tisch4Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tisch5Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tisch6Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Tischverwaltung().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Tisch1Panel;
    private javax.swing.JLabel Tisch1PersonenLabel;
    private javax.swing.JLabel Tisch1StatusLabel;
    private javax.swing.JLabel Tisch2NameLabel;
    private javax.swing.JPanel Tisch2Panel;
    private javax.swing.JLabel Tisch2PersonenLabel;
    private javax.swing.JLabel Tisch2StatusLabel;
    private javax.swing.JLabel Tisch3NameLabel;
    private javax.swing.JPanel Tisch3Panel;
    private javax.swing.JLabel Tisch3PersonenLabel;
    private javax.swing.JLabel Tisch3StatusLabel;
    private javax.swing.JLabel Tisch4NameLabel;
    private javax.swing.JPanel Tisch4Panel;
    private javax.swing.JLabel Tisch4PersonenLabel;
    private javax.swing.JLabel Tisch4StatusLabel;
    private javax.swing.JLabel Tisch5NameLabel;
    private javax.swing.JPanel Tisch5Panel;
    private javax.swing.JLabel Tisch5PersonenLabel;
    private javax.swing.JLabel Tisch5StatusLabel;
    private javax.swing.JLabel Tisch6NameLabel;
    private javax.swing.JPanel Tisch6Panel;
    private javax.swing.JLabel Tisch6PersonenLabel;
    private javax.swing.JLabel Tsich6StatusLabel;
    private javax.swing.JLabel UeberschriftLabel;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
